# Generated by Django 5.0.3 on 2026-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuente IPTV',
                'verbose_name_plural': 'Fuentes IPTV',
            },
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.AddField(
            model_name='channel',
            name='bitrate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
