# Generated by Django 5.0.3 on 2026-07-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0002_iptvsource_alter_channel_options_channel_bitrate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptvsource',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Fuente IPTV', 'verbose_name_plural': 'Fuentes IPTV'},
        ),
        migrations.AddField(
            model_name='iptvsource',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iptvsource',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='iptvsource',
            name='total_channels',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
