# Generated by Django 5.0.3 on 2026-07-22 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0003_alter_iptvsource_options_iptvsource_auto_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['name'], 'verbose_name': 'Canal', 'verbose_name_plural': 'Canales'},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='is_live',
            new_name='is_public',
        ),
        migrations.AddField(
        model_name='channel',
        name='watching_now',
        field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='epg_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='quality',
            field=models.CharField(choices=[('SD', 'SD'), ('HD', 'HD'), ('FHD', 'Full HD'), ('4K', '4K')], default='HD', max_length=10),
        ),
        migrations.AddField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[('checking', 'Verificando'), ('online', 'Online'), ('offline', 'Offline')], default='checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia_tv.category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia_tv.country'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia_tv.language'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='stream_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_tv.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_tv.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
