# Generated by Django 5.0.3 on 2026-07-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0004_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='bitrate',
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='guia_tv.category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='guia_tv.country'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='guia_tv.language'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['name'], name='guia_tv_cha_name_957fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['slug'], name='guia_tv_cha_slug_6883d4_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['is_active'], name='guia_tv_cha_is_acti_287596_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['is_featured'], name='guia_tv_cha_is_feat_b6fea1_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['country'], name='guia_tv_cha_country_b48c16_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['category'], name='guia_tv_cha_categor_ed67fd_idx'),
        ),
    ]
