# Generated by Django 5.0.3 on 2026-07-30 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0005_remove_channel_bitrate_alter_channel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='audio_codec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='channel',
            name='bitrate',
            field=models.PositiveIntegerField(default=0, help_text='Bitrate en kbps'),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='resolution',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='channel',
            name='response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='guia_tv.iptvsource'),
        ),
        migrations.AddField(
            model_name='channel',
            name='stream_type',
            field=models.CharField(choices=[('HLS', 'HLS (.m3u8)'), ('MPD', 'MPEG-DASH'), ('TS', 'MPEG-TS'), ('RTMP', 'RTMP'), ('OTHER', 'Otro')], default='HLS', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='tvg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='tvg_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='epg_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['language'], name='guia_tv_cha_languag_26e29c_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['status'], name='guia_tv_cha_status_1c4bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tvg_id'], name='guia_tv_cha_tvg_id_7cdcf7_idx'),
        ),
    ]
