# Generated by Django 5.0.3 on 2026-07-31 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0007_channel_license_note_channel_license_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Principal', max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('stream_type', models.CharField(choices=[('HLS', 'HLS (.m3u8)'), ('MPD', 'MPEG-DASH'), ('TS', 'MPEG-TS'), ('RTMP', 'RTMP'), ('OTHER', 'Otro')], default='HLS', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_working', models.BooleanField(default=True)),
                ('response_time', models.FloatField(default=0)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programación',
                'ordering': ['start'],
            },
        ),
        migrations.RenameIndex(
            model_name='channel',
            new_name='guia_tv_cha_license_293cc1_idx',
            old_name='guia_tv_cha_license_9f6f39_idx',
        ),
        migrations.AddField(
            model_name='channelstream',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='guia_tv.channel'),
        ),
        migrations.AddField(
            model_name='program',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='guia_tv.channel'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['channel'], name='guia_tv_pro_channel_f37e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['start'], name='guia_tv_pro_start_931f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['end'], name='guia_tv_pro_end_a65bd0_idx'),
        ),
    ]
