# Generated by Django 5.0.3 on 2026-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_tv', '0008_channelstream_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='source',
        ),
        migrations.AddField(
            model_name='channel',
            name='source_type',
            field=models.CharField(choices=[('iptv', 'IPTV'), ('youtube', 'YouTube'), ('twitch', 'Twitch')], default='iptv', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='channel',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bitrate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='license_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='license_status',
            field=models.CharField(choices=[('pending', 'Pendiente de revisión'), ('official', 'Oficial del canal/organismo'), ('public_domain', 'Dominio público / licencia abierta'), ('rejected', 'Rechazado (posibles derechos de autor)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='stream_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
